### PR TITLE
nodejs: down to 18

### PR DESCRIPTION
**Pull request by cdmistman**
Why
===

we want to support many node versions! all the way down to 18 in fact!

What changed
============

- added node 20
- added node 19
- added node 18

Test plan
=========

all print the expected versions:
```sh
nix run '.#nodejsVersions."20.12.1"' -- --version
nix run '.#nodejsVersions."19.9.0"' -- --version
nix run '.#nodejsVersions."18.20.1"' -- --version
```

### CODE REVIEW

**Comment by cdmistman** [comment]
ope forgot to test with the patches

**Comment by cdmistman** [comment]
node 20 fails checks (it didn't yesterday 😞) and node 18 fails to build, digging into why

**Comment by cdmistman** [comment]
successfully got node 18 building! will amend this pr in the morning to include that change

**Review by blast-hardcheese — APPROVED** [review]
Looks sensible

**Pull request merged**
